#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'getTotalX' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#

def getTotalX(a, b):
    f=min(len(a),len(b))
    c=list(set((a)+(b)))
    
    e=0
    # print(c)
    # c=sorted(c)
    for i in range(max(a),min(b)):
        d=0
        for j in range(len(c)):
            
            if c[j]<min(b):
                
                    if i%c[j]==0:
                        d+=1
                    
            else:
               if c[j]%i==0:
                d+=1
        if d==len(c):
            e+=1
    if e==0:
        return 0
    if f==1 and len(a)!=len(b):
        return e
    return e+1
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    arr = list(map(int, input().rstrip().split()))

    brr = list(map(int, input().rstrip().split()))

    total = getTotalX(arr, brr)

    fptr.write(str(total) + '\n')

    fptr.close()
