#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'funnyString' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def funnyString(s):
  w=[]
  e=[]
  r=len(s)-1
  for i in range(len(s)):
    w.append(ord(s[i]))
    e.append(ord(s[r]))
    r-=1
  print(w,e)
  for i in range(len(w)-1):
    if abs(w[i]-w[i+1])==abs(e[i]-e[i+1]):
        continue
    else:
        return 'Not Funny'
  return 'Funny'
    
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        result = funnyString(s)

        fptr.write(result + '\n')

    fptr.close()
