#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'marsExploration' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING s as parameter.
#

def marsExploration(s):
    c=0
    for i in range(len(s)):
        t=i%3
        if t==0:
            if s[i]!='S':
                c+=1
        elif t==1:
            if s[i]!='O':
                c+=1
        elif t==2:
            if s[i]!='S':
                c+=1
    return c   

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = marsExploration(s)

    fptr.write(str(result) + '\n')

    fptr.close()
