#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'minimumDistances' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def minimumDistances(a):
    c=len(a)
    d=list(set(a))
    if c==len(d):
        return -1
    for i in range(len(a)):
        for j in range(len(a)):
            if i == j:
                continue
            else:
                if a[i]==a[j]:
                    if abs(j-i)<c:
                        print(c)
                        c=(j-i)
    return c
                    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = minimumDistances(a)

    fptr.write(str(result) + '\n')

    fptr.close()
