#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pangrams' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#
#3408
def pangrams(s):
    c=0
    if len(s)<26:
        return "not pangram"
    a=s.casefold()
    d=list(a)
    d.remove(' ')
    e=list(set(d))
    print(e)
    e.remove(' ')
    if len(e)==26:
        return "pangram"   
    else:
        return "not pangram"   

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = pangrams(s)

    fptr.write(result + '\n')

    fptr.close()
