#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'squares' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER a
#  2. INTEGER b
#

def squares(a, b):
    c=0
    # for i in range(a,b+1):
    #     if math.sqrt(i)==int(math.sqrt(i)):
    #         c+=1
    i=int(math.sqrt(a))
    print(i)
    while i**2<=b:
        print(i**2)
        if i**2>=a and i**2<=b:
            c+=1
        i+=1
    return c
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        first_multiple_input = input().rstrip().split()

        a = int(first_multiple_input[0])

        b = int(first_multiple_input[1])

        result = squares(a, b)

        fptr.write(str(result) + '\n')

    fptr.close()
