#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'minimumNumber' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. STRING password
#

def minimumNumber(n, password):
    r=4
    
    # if len(password)>=6:
    #     r-=1
    a=0
    b=0
    c=0
    d=0
    for i in range(len(password)):
        print(r)
        if password[i].isdigit() and a==0:
            r-=1
            a=1
        elif password[i].islower() and b==0:
            r-=1
            b=1
        elif password[i].isupper() and c==0:
            r-=1
            c=1
        elif (password[i]=='!' or password[i]=='@' or password[i]=='#' or password[i]=='$' or password[i]=='%' or password[i]=='^' or password[i]=='&' or password[i]=='*' or password[i]=='(' or password[i]==')' or password[i]=='-' or password[i]=='+' )and d==0:
            r-=1
            d=1
    print(r)
    if len(password)<=6:
        if r+len(password)<6:
            return 6-len(password)
    return r  
    
        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    password = input()

    answer = minimumNumber(n, password)

    fptr.write(str(answer) + '\n')

    fptr.close()
