#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'superReducedString' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def superReducedString(s):
    i=0
    a=list(s)
    b=1
    c=0
    while b:
        c=0
        i=0
        # for i in range(len(a)-1):
        while i<len(a)-1:
            if i>len(a)-2:
                break
            if a[i]==a[i+1]:
                 a.pop(i)
                 a.pop(i)
                 c+=1
            
            print(a)
            if len(a)==0:
                return 'Empty String'
            
            if len(list(set(a)))==len(a):
                print(1)
                d=''
                for e in a:
                    d+=e
                return d
                b=0
            i+=1
        i=0
        if c==0:
            d=''
            print(a)
            for e in a:
                d+=e
            return d
                
    return str(a)
    # while len(a)!=0 or i<(len(a)-2):
    #     if a[i]==a[i+1]:
    #         a.pop(i)
    #         a.pop(i+1)
    #         if len(a)==0:
    #             return 'Empty String'
    #     print(a)
        # i+=1
        # if len(list(set(a)))==len(a):
        #     break
        # if i==len(len(a)-2):
        #     i=0
    
                
        
        
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = superReducedString(s)

    fptr.write(result + '\n')

    fptr.close()
