#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'taumBday' function below.
#
# The function is expected to return a LONG_INTEGER.
# The function accepts following parameters:
#  1. INTEGER b
#  2. INTEGER w
#  3. INTEGER bc
#  4. INTEGER wc
#  5. INTEGER z
#

def taumBday(b, w, bc, wc, z):
    a=[]
    c=0
    h=(b*bc)+(w*wc)
    g=0
    if bc==wc:
        return h
    a.append(c)
    if wc>bc:
        c=0
        z1=w
        w=0
        
        c=(b*bc)+(w*wc)+z*z1
        return min(c,h)
    else:
        w+=b
        z1=b
        b=0
        c=(b*bc)+(w*wc)+z*z1
        return min(c,h)
    print(a)
    return min(a)   
            
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        first_multiple_input = input().rstrip().split()

        b = int(first_multiple_input[0])

        w = int(first_multiple_input[1])

        second_multiple_input = input().rstrip().split()

        bc = int(second_multiple_input[0])

        wc = int(second_multiple_input[1])

        z = int(second_multiple_input[2])

        result = taumBday(b, w, bc, wc, z)

        fptr.write(str(result) + '\n')

    fptr.close()
  
